# Generated by Django 4.2.4 on 2024-02-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('id_no', models.CharField(max_length=10)),
                ('degree_name', models.CharField(max_length=20)),
                ('admission_session', models.CharField(max_length=20)),
                ('passing_year', models.DateField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
